Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieShop.Data;
using MovieShop.Extensions;
using MovieShop.Models.Db;
using MovieShop.Services;
using Newtonsoft.Json;

namespace MovieShop.Controllers
{
    public class CartController : Controller
    {
        private readonly CartService _cartService;
        private readonly interstellardb _interstellardb;

        public CartController(CartService cartService, interstellardb interstellardb)
        {
            _cartService = cartService;
            _interstellardb = interstellardb;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AddToCart(int movieId)
        {
            return View();
        }
        [HttpPost, ActionName("AddToCart")]
        public IActionResult AddToShoppingCart(int movieId, [Bind("Id, Title,Director,ReleaseYear,Price")] Movie movie)
        {
            //Checks the shopping cart received from session, 
            // you initialize the list otherwise it returns
            //  if it is null,the list from the session
            
            var cartList = HttpContext.Session.Get<List<int>>("ShoppingCart")?? new List<int> { }; 
            cartList.Add(movieId); //add the movieId to the list
            _cartService.AddMovieToCart(movie.Id);
            var numberOfListItems = cartList.Count(); //counts and adds the count to numberoflistitems
            HttpContext.Session.Set<List<int>>("ShoppingCart", cartList); //reset the shopping list and store in session                
            return Json(numberOfListItems);
        }

        public IActionResult DisplayCart()
        {
            var movieCartItems = _cartService.DisplayCart();
            if (movieCartItems.Count > 0)
            {
                return View(movieCartItems);
            }
            else
            {
                return RedirectToAction("EmptyCartMessage");
            }
        }

        public IActionResult EmptyCartMessage()
        {
            return View();
        }

        public IActionResult PlacingOrder()
        {
            return View();
        }

        public IActionResult GettingCartCount()
        {
            var cartList = HttpContext.Session.Get<List<int>>("ShoppingCart");
            //Display the count of cart
            var numberOfListItems = cartList.Count();
            HttpContext.Session.Set<List<int>>("ShoppingCart", cartList);

            // get the movie from DB and pass it as parameter 
            // AddMovieToCart is a method
            // it adds movie obj, copies of movie
            return Json(numberOfListItems);
        }

        [HttpPost]
        public IActionResult Checkout()
        {
            var email = Request.Form["customerEmail"];
            _cartService.CustomerCheckout(email);
            Console.WriteLine(email);
            return View();
        }

        public IActionResult GettingNewCustomer()
        {
            return View();
        }

   
        [HttpPost]
        public IActionResult CreateNewCustomer()
        {
            Customer customer = new Customer();
            var fname = Request.Form["FirstName"];
            var lname = Request.Form["LastName"];
            var billingaddr = Request.Form["BillingAddr"];
            var billingzip = Request.Form["BillingZip"];
            var billingcity = Request.Form["BillingCity"];
            var deliveryaddr = Request.Form["DeliveryAddr"];
            var deliveryzip = Request.Form["DeliveryZip"];
            var deliverycity = Request.Form["DeliveryCity"];
            var emailaddr = Request.Form["EmailAddr"];
            var phoneno = Request.Form["PhoneNo"];
            customer.Firstname = fname;
            customer.Lastname = lname;
            customer.BillingAddress = billingaddr;
            customer.BillingCity = billingcity;
            customer.BillingZip = Int32.Parse(billingzip);
            customer.DeliveryAddress = deliveryaddr;
            customer.DeliveryCity = deliverycity;
            customer.DeliveryZip = Int32.Parse(deliveryzip);
            customer.EmaillAddress = emailaddr;
            customer.PhoneNo = phoneno;
            _cartService.AddingNewCustomer(customer);
            return RedirectToAction("PlacingOrder");
        }
        public IActionResult AddItem(int movieid)
        {
            _cartService.IncreaseCopy(movieid);
            return View();
        }

        public IActionResult ReduceItem(int movieid)
        {
            _cartService.DecreaseCopy(movieid);
            return View();
        }
    }
}

Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using MovieShop.Services;
using MovieShop.Models.Db;
using Microsoft.EntityFrameworkCore;

namespace MovieShop.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ICustomerServices _customerService;
        public CustomersController(ICustomerServices customerService)
        {
            _customerService = customerService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create() 
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Create(Customer customer) 
        {
            _customerService.Create(customer);
            return RedirectToAction("CustCreateSuccessMessage");
        }
        public IActionResult Details() 
        {
            var customerlist = _customerService.Display();
            return View(customerlist); 
        }

        public IActionResult EnterEmail()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UpdateCustomer()
        {
           var email = Request.Form["Email"];
           var customer = _customerService.GetCustomerByemail(email);
            if (customer == null)
            { 
                return RedirectToAction("CustomerNotFound");
            }
           return View(customer);
        }

        //[HttpPost]

        public IActionResult SaveCustomer(Customer customer)
        {
            if (ModelState.IsValid) { 
                _customerService.UpdateCustomer(customer);
                return RedirectToAction("Success");
            }
            return RedirectToAction("Success");
        }

        public IActionResult Success()
        {
            return View();
        }

        public IActionResult CustCreateSuccessMessage()
        {
            return View();
        }
        public IActionResult CustomerMenu()
        {
            return View();
        }
        public IActionResult CustomerEmail()
        {
            return View();  
        }

        [HttpPost]
        public IActionResult CustomerOrders()
        {
            var email = Request.Form["Email"];
            var customerOrder = _customerService.GetCustomerOrders(email);
            if (customerOrder.Count == 0)
            {
                return RedirectToAction("CustomerEmailNotFound");
               
            }
            return View(customerOrder);

        }

        public IActionResult CustomerNotFound()
        {
            return View();
        }

        public IActionResult CustomerEmailNotFound()
        {
            return View();
        }

    }
}

Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using MovieShop.Data;
using MovieShop.Models.Db;
using MovieShop.Services;
using System.Dynamic;
namespace MovieShop.Controllers
{
    public class MoviesController : Controller
    {

        private readonly IMovieServices _movieService;
        private readonly ICustomerServices _customerService;
        private readonly interstellardb _db;

        public MoviesController(IMovieServices movieService, ICustomerServices customerService, interstellardb db)
        {
            _movieService = movieService;
            _customerService = customerService;
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Movie movie)
        {
            _movieService.Create(movie);
            return RedirectToAction("CreateSuccessMessage");
        }
        public IActionResult Details()
        {
            var movielist = _movieService.Display();
            return View(movielist);
        }

        public IActionResult Update(Movie movie)
        {
            var movielist = _movieService.Display();
            return View(movielist);
        }

        public IActionResult GenreBasedMovies(string genre)
        {
            var movies = _movieService.MoviesListGenre(genre);
            return View(movies);
        }

        public IActionResult MovieMenu()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var movie = _movieService.GetMovieById(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit(Movie movie)
        {
            _movieService.Editmovie(movie);
            return RedirectToAction("UpdateSuccessMessage");
        }

        public IActionResult UpdateSuccessMessage()
        {
            return View();
        }

        public IActionResult CreateSuccessMessage()
        {
            return View();
        }

        public IActionResult ShowAllOrders()
        {
            var orders = _movieService.GetAllOrders();
            return View(orders);
        }

        public IActionResult List(int length = 6, int page = 1)
        {

            //fetch list of movies

            var moviesList = _movieService.GetPaginatedMovies(length, page);
            ViewBag.Page = page;
            ViewBag.Length = length;
            ViewBag.TotalCount = _db.Movies.Count();
            return View(moviesList);

        }

    }
}

Views/Movies/Create.cshtml
@model MovieShop.Models.Db.Movie

@{
    ViewData["Title"] = "Create";
}


<div id="title" class="col-sm-12">
    &nbsp; Create Movie Details
</div>

<br />
<div class="row">
    <div class="col-sm-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <strong>
                    <label asp-for="Title" class="control-label"></label>
                </strong>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Director" class="control-label"></label>
                </strong>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Genre" class="control-label"></label>
                </strong>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Release_Year" class="control-label"></label>
                </strong>
                <input asp-for="Release_Year" class="form-control" />
                <span asp-validation-for="Release_Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Price" class="control-label"></label>
                </strong>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TargetUrl" class="control-label"></label>
                </strong>
                <input asp-for="TargetUrl" class="form-control" />
                <span asp-validation-for="TargetUrl" class="text-danger"></span>
            </div>
            <hr>
            <div class="form-group">
                <input type="submit" value="Create" class="btn text-white bg-black bg-gradient" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<style>
    #title {
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
        margin-top: 30px;
    }
</style>

Views/Movies/CreateSuccessMessage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="div" class="col-sm-3 card" style="width: 25rem;">
    <img src="~/Images/filmRoll.jpg" class="card-img-top" style="height:150px; width:150px" />
    <br />
    <div class="card-body col-sm-3 bg-dark">
        <h5 class="card-title text-white">Successfully Movie Created</h5>
    </div>
</div>

<style>
    #div {
        margin-top: 200px;
        margin-left: 200px;
        align-items: center;
        font-family: 'Comic Sans MS';
    }
</style>

Views/Movies/Details.cshtml
@model IEnumerable<MovieShop.Models.Db.Movie>

@{
    ViewData["Title"] = "Details";
}

<br />
<br />
<div class="col-sm" id="title">
    &nbsp; Movie List
</div>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-9">
            <partial name="_MoviePartial" model="item" /><br />
        </div>
    }
</div>
<div>
    <a class="btn btn-danger" asp-controller="Cart" asp-action="DisplayCart">Go to Cart</a>
</div>

<style>
    #title {
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
    }
</style>

Views/Movies/Edit.cshtml
@model MovieShop.Models.Db.Movie

@{
    ViewData["Title"] = "Edit";
}

<div class="col-sm-12" id="title">
    Edit Movie Details
</div>
<br />
<div class="row">
    <div class="col-sm-6">
        <form asp-action="Edit" asp-method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <strong>
                    <label asp-for="Title" class="control-label"></label>
                </strong>
                <input asp-for="Title" class="form-control" value="@Model.Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Director" class="control-label"></label>
                </strong>
                <input asp-for="Director" class="form-control" value="@Model.Director" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Genre" class="control-label"></label>
                </strong>
                <input asp-for="Genre" class="form-control" value="@Model.Genre" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Release_Year" class="control-label"></label>
                </strong>
                <input asp-for="Release_Year" class="form-control" value="@Model.Release_Year" />
                <span asp-validation-for="Release_Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="Price" class="control-label"></label>
                </strong>
                <input asp-for="Price" class="form-control" value="@Model.Price" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <strong>
                    <label asp-for="TargetUrl" class="control-label"></label>
                </strong>
                <input asp-for="TargetUrl" class="form-control" value="@Model.TargetUrl" />
                <span asp-validation-for="TargetUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <hr />
                <input type="submit" value="Update" class="btn text-white bg-black bg-gradient" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<style>
    #title {
        width: 900px;
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
        margin-top : 30px;
    }
</style>

Views/Movies/GenreBasedMovies.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<MovieShop.Models.Db.Movie>

@{
    ViewData["Title"] = "Display";
}

<div class="col-sm-3" id="title">
    Genre Based Movie List
</div>
<br />


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-3">
            <partial name="_MoviePartial" model="item" /><br />
        </div>
    }
</div>

<hr />
<div style="background-color:black; width:100%">
    <a class="btn btn-black bg-gradient text-white" asp-controller="Cart" asp-action="DisplayCart">Go To Cart</a>
</div>

<style>
    #title {
        width: 1000px;
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
    }
</style>

Views/Movies/List.cshtml
@model IEnumerable<MovieShop.Models.Db.Movie>

@{
    ViewData["Title"] = "List";
}

<div id="title" class="col-sm-3">
    Movie List
</div>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-3">
            <partial name="_MoviePartial" model="item" /><br />
        </div>
    }
</div>

<hr />
<div>
    @if (ViewBag.Page > 1)
    {
        <a class="btn btn-sm btn-secondary" href="?page=@(ViewBag.Page - 1)&length=@ViewBag.Length"> Previous </a>
    }

    <span class="fw-bold text-bg-info">
        &nbsp;&nbsp; Page @ViewBag.Page of
        @(Math.Ceiling((decimal)ViewBag.TotalCount / ViewBag.Length))
    </span> &nbsp;&nbsp;

    @if(ViewBag.Page < 
    Math.Ceiling((decimal)ViewBag.TotalCount / ViewBag.Length))
    {
        <a class="btn btn-sm btn-secondary" href="?page=@(ViewBag.Page + 1)&length =@ViewBag.Length"> Next </a>

    }

    <a id="gotocart" class="btn btn-danger" asp-controller="Cart" asp-action="DisplayCart">Go to Cart</a>    
   
</div>

<style>
    #gotocart{
        margin-left:450px;
    }

    #title {
        width: 1000px;
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
    }
</style>

Views/Movies/Menu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<button>
    Create Movie
</button>

@Html.ActionLink("Create a movie", "Create", "Movies")

@Html.ActionLink("Update a movie", "Update", "Movies")

@Html.ActionLink("Orders", "ShowAllOrders", "Movies")

Views/Movies/MovieMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="maindiv" class="col-sm-12">

<div id="border"></div>

    <div id="title" class="align-middle text-white">
        <h6 style="color:darkgoldenrod">&nbsp; Administrator Functionalities</h6>
        <hr />
        <a class="btn bg-gradient text-white" asp-controller="Movies" asp-action="Create">
            Create Movie
        </a>
        <hr />
        <a class="btn bg-gradient text-white" asp-controller="Movies" asp-action="Update">
            Update Movie
        </a><hr />
        <a class="btn bg-gradient text-white" asp-controller="Movies" asp-action="ShowAllOrders">
            View Orders
        </a><hr />
        <a class="btn bg-gradient text-white" asp-controller="Customers" asp-action="Details">
            Customer Details
        </a>&nbsp;
        
    </div>

<div id="border"></div>
</div>
<style>
    #title {
        background-color: black;
        padding: 10px 0px 0px 5px;
        font-weight: bold;
    }

   #maindiv {
        width: 25%;
        margin: 50px 0px 0px 200px;
   }
    #border {
        height: 15px;
        background-color: darkgoldenrod;
    }
</style>

Views/Movies/ShowAllOrders.cshtml
@model IEnumerable<MovieShop.Models.ViewModels.AdminOrder>
@{
    ViewData["Title"] = "ShowAllOrders";
}


<br />
<br />
<div class="col-sm-12" id="title">
    &nbsp; Movie Shop Order Details
</div>
<br />
<table class="table table-bordered table-striped table-sm align-middle">
    <tr>
        <th style="width:20px">Order ID</th>
        <th style="width:70px">Order Date</th>
        <th style="width:60px">Order Count</th>
        <th style="width:130px">Customer Name</th>
        <th style="width:200px">Movie Title/Price</th>
        <th style="width:70px">Order Amount</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.OrderId</td>
            <td>@item.DateOfPurchase</td>
            <td>@item.TotalOrderCount</td>
            <td>@item.CustomerName</td>
            <td>
                @foreach (var movie in item.Movies)
                {
                    <p>
                        @movie.Title
                        <span style="color:blue">
                            [ SEK @movie.Price ]
                        </span>
                    </p>

                    <hr />
                }
            </td>
            <td>@item.TotalOrderCost</td>
        </tr>
    }
</table>

<style>
    #title {
        width: 1000px;
        height: 25px;
        background-color: dimgray;
        color: white;
        font-weight: bold;
    }
</style>

Views/Movies/Update.cshtml
@model IEnumerable<MovieShop.Models.Db.Movie>

@{
    ViewData["Title"] ="Update";
}

<div class="col-sm-12" id="title">
    &nbsp; Update Movie Details
</div>
<br />
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-3">
            <div class="card" style="width:220px;height:400px">
                <img class="card-img-top" src="@item.TargetUrl" style="height:250px">
                <div class="card-body fw-bold" style="background-color:black">
                    <h6>@item.Title</h6>
                    <h6>@item.Director </h6>
                    <h6>@item.Release_Year |@item.Genre | @item.Price SEK</h6>
                    
                    <a class="btn bg-secondary bg-gradient text-white" asp-action="Edit" asp-route-id="@item.Id">
                       UPDATE
                    </a>
                </div>
            </div><br />
        </div>
    }
</div>

<style>
    .card {
        font-family:'David Libre';
        font-weight:bold;
        color:white;
    }

    .card-footer {
        padding-left: 50px;
        padding-top: 12px;
    }
    #title { 
        width:900px;
        height:25px;
        background-color:dimgrey; 
        color:white;
        font-weight:bold;
        margin-top : 30px;
    }
</style>






    

Views/Movies/UpdateSuccessMessage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="div" class="card col-sm" style="width: 25rem;">
    <img src="~/Images/filmRoll.jpg" class="card-img-top" style="height:150px; width:150px" />
    <br />
    <div class="card-body bg-dark">
        <h5 class="card-title text-white">Successfully Movie Updated</h5>
    </div>
</div>

<style>
    #div {
        margin-top: 100px;
        margin-left: 200px;
        align-items: center;
        font-family: 'Comic Sans MS';
    }
</style>